import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

test('vendored files match SHA256SUMS', () => {
  const sums = readFileSync('vendor/viz/SHA256SUMS', 'utf8').trim().split('\n');
  assert.ok(sums.length > 0);
  for (const line of sums) {
    const [expected, name] = line.split(/\s+/) as [string, string];
    const actual = createHash('sha256').update(readFileSync(`vendor/viz/${name}`)).digest('hex');
    assert.equal(actual, expected, name);
  }
});

test('vendored viz is Graphviz 16.0.0 and renders svg_inline synchronously', async () => {
  const { instance } = require('../vendor/viz/viz.cjs');
  const viz = await instance();
  assert.equal(viz.graphvizVersion, '16.0.0');
  const result = viz.render('digraph { a -> b }', { format: 'svg_inline' });
  assert.equal(result.status, 'success');
  // svg_inline has no XML prolog or stylesheet processing instruction, but it does lead with
  // generator comments and its root <svg> carries no xmlns — the sanitizer has to expect both.
  assert.match(result.output, /^<!-- Generated by graphviz version 16\.0\.0/);
  assert.match(result.output, /<svg width=/);
  assert.doesNotMatch(result.output, /<svg[^>]*xmlns=/);
  assert.doesNotMatch(result.output, /<\?xml/);
});

test('vendored viz reports syntax errors with a line number', async () => {
  const { instance } = require('../vendor/viz/viz.cjs');
  const viz = await instance();
  const result = viz.render('digraph { a -> ; }', { format: 'svg_inline' });
  assert.equal(result.status, 'failure');
  assert.match(result.errors[0].message, /syntax error in line 1/);
});
